//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analizator9000 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analizator9000.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiza zakończona. Wyniki w pliku.
        /// </summary>
        internal static string Accumulator_analysisFinished {
            get {
                return ResourceManager.GetString("Accumulator_analysisFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiza przewana. Częściowe wyniki w pliku.
        /// </summary>
        internal static string Accumulator_analysisInterrupted {
            get {
                return ResourceManager.GetString("Accumulator_analysisInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podano pusty zbiór rozdań.
        /// </summary>
        internal static string Accumulator_errorNoDeals {
            get {
                return ResourceManager.GetString("Accumulator_errorNoDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gra w.
        /// </summary>
        internal static string Accumulator_playsIn {
            get {
                return ResourceManager.GetString("Accumulator_playsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lew.
        /// </summary>
        internal static string Accumulator_tricks {
            get {
                return ResourceManager.GetString("Accumulator_tricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można wczytać rozdania.
        /// </summary>
        internal static string BCalcWrapper_dealLoadError {
            get {
                return ResourceManager.GetString("BCalcWrapper_dealLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy rozgrywający.
        /// </summary>
        internal static string BCalcWrapper_declarerError {
            get {
                return ResourceManager.GetString("BCalcWrapper_declarerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe miano.
        /// </summary>
        internal static string BCalcWrapper_trumpError {
            get {
                return ResourceManager.GetString("BCalcWrapper_trumpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za duża wartość &apos;generate&apos;.
        /// </summary>
        internal static string DealerParser_errorGenerateOverflow {
            get {
                return ResourceManager.GetString("DealerParser_errorGenerateOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za duża wartość &apos;produce&apos;.
        /// </summary>
        internal static string DealerParser_errorProduceOverflow {
            get {
                return ResourceManager.GetString("DealerParser_errorProduceOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbyt duża liczba wartości &apos;generate&apos; w skrypcie.
        /// </summary>
        internal static string DealerParser_errorTooManyGenerate {
            get {
                return ResourceManager.GetString("DealerParser_errorTooManyGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbyt duża liczba linii &apos;produce&apos; w skrypcie.
        /// </summary>
        internal static string DealerParser_errorTooManyProduce {
            get {
                return ResourceManager.GetString("DealerParser_errorTooManyProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono pliku.
        /// </summary>
        internal static string DealerWrapper_errorFileNotFound {
            get {
                return ResourceManager.GetString("DealerWrapper_errorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowa liczba rozdań do wyprodukowania.
        /// </summary>
        internal static string DealerWrapper_errorInvalidDealCount {
            get {
                return ResourceManager.GetString("DealerWrapper_errorInvalidDealCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd analizy.
        /// </summary>
        internal static string Form1_analyzeError {
            get {
                return ResourceManager.GetString("Form1_analyzeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie podano kontraktów.
        /// </summary>
        internal static string Form1_analyzeNoContractsError {
            get {
                return ResourceManager.GetString("Form1_analyzeNoContractsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik nie zawiera żadnych rozdań.
        /// </summary>
        internal static string Form1_analyzeNoDealsError {
            get {
                return ResourceManager.GetString("Form1_analyzeNoDealsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwieram plik.
        /// </summary>
        internal static string Form1_analyzeOpenFile {
            get {
                return ResourceManager.GetString("Form1_analyzeOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string Form1_error {
            get {
                return ResourceManager.GetString("Form1_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksport do PBN zakończony. Plik wynikowy.
        /// </summary>
        internal static string Form1_exportSuccess {
            get {
                return ResourceManager.GetString("Form1_exportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd wczytywania pliku.
        /// </summary>
        internal static string Form1_fileOpenError {
            get {
                return ResourceManager.GetString("Form1_fileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można utworzyć pliku. Sprawdź, czy w katalogu programu istnieje katalog &apos;files&apos;.
        /// </summary>
        internal static string Form1_generateFileNotFoundError {
            get {
                return ResourceManager.GetString("Form1_generateFileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano do pliku.
        /// </summary>
        internal static string Form1_generateFileSaved {
            get {
                return ResourceManager.GetString("Form1_generateFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd generatora.
        /// </summary>
        internal static string Form1_generateGeneratorError {
            get {
                return ResourceManager.GetString("Form1_generateGeneratorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd wprowadzania danych.
        /// </summary>
        internal static string Form1_generateInputError {
            get {
                return ResourceManager.GetString("Form1_generateInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMP.
        /// </summary>
        internal static string ScoreAccumulator_IMP {
            get {
                return ResourceManager.GetString("ScoreAccumulator_IMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        internal static string ScoreAccumulator_MP {
            get {
                return ResourceManager.GetString("ScoreAccumulator_MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  KONTRAKT      LEWY    ZAPIS   WYGRA?  MAX    IMP.
        /// </summary>
        internal static string ScoreAccumulator_txtHeader {
            get {
                return ResourceManager.GetString("ScoreAccumulator_txtHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obie po.
        /// </summary>
        internal static string ScoreAccumulator_vulBoth {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EW po.
        /// </summary>
        internal static string ScoreAccumulator_vulEW {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Założenia.
        /// </summary>
        internal static string ScoreAccumulator_vulnerability {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obie przed.
        /// </summary>
        internal static string ScoreAccumulator_vulNone {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NS po.
        /// </summary>
        internal static string ScoreAccumulator_vulNS {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulNS", resourceCulture);
            }
        }
    }
}
