//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34209
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analizator9000 {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analizator9000.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Zastępuje właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Analiza zakończona. Wyniki w pliku.
        /// </summary>
        internal static string Accumulator_analysisFinished {
            get {
                return ResourceManager.GetString("Accumulator_analysisFinished", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Analiza przewana. Częściowe wyniki w pliku.
        /// </summary>
        internal static string Accumulator_analysisInterrupted {
            get {
                return ResourceManager.GetString("Accumulator_analysisInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podano pusty zbiór rozdań.
        /// </summary>
        internal static string Accumulator_errorNoDeals {
            get {
                return ResourceManager.GetString("Accumulator_errorNoDeals", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu gra w.
        /// </summary>
        internal static string Accumulator_playsIn {
            get {
                return ResourceManager.GetString("Accumulator_playsIn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu lew.
        /// </summary>
        internal static string Accumulator_tricks {
            get {
                return ResourceManager.GetString("Accumulator_tricks", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można wczytać rozdania.
        /// </summary>
        internal static string BCalcWrapper_dealLoadError {
            get {
                return ResourceManager.GetString("BCalcWrapper_dealLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieprawidłowy rozgrywający.
        /// </summary>
        internal static string BCalcWrapper_declarerError {
            get {
                return ResourceManager.GetString("BCalcWrapper_declarerError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieprawidłowe miano.
        /// </summary>
        internal static string BCalcWrapper_trumpError {
            get {
                return ResourceManager.GetString("BCalcWrapper_trumpError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Za duża wartość &apos;generate&apos;.
        /// </summary>
        internal static string DealerParser_errorGenerateOverflow {
            get {
                return ResourceManager.GetString("DealerParser_errorGenerateOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Za duża wartość &apos;produce&apos;.
        /// </summary>
        internal static string DealerParser_errorProduceOverflow {
            get {
                return ResourceManager.GetString("DealerParser_errorProduceOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zbyt duża liczba wartości &apos;generate&apos; w skrypcie.
        /// </summary>
        internal static string DealerParser_errorTooManyGenerate {
            get {
                return ResourceManager.GetString("DealerParser_errorTooManyGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zbyt duża liczba linii &apos;produce&apos; w skrypcie.
        /// </summary>
        internal static string DealerParser_errorTooManyProduce {
            get {
                return ResourceManager.GetString("DealerParser_errorTooManyProduce", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono pliku.
        /// </summary>
        internal static string DealerWrapper_errorFileNotFound {
            get {
                return ResourceManager.GetString("DealerWrapper_errorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieprawidłowa liczba rozdań do wyprodukowania.
        /// </summary>
        internal static string DealerWrapper_errorInvalidDealCount {
            get {
                return ResourceManager.GetString("DealerWrapper_errorInvalidDealCount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd analizy.
        /// </summary>
        internal static string Form1_analyzeError {
            get {
                return ResourceManager.GetString("Form1_analyzeError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie podano kontraktów.
        /// </summary>
        internal static string Form1_analyzeNoContractsError {
            get {
                return ResourceManager.GetString("Form1_analyzeNoContractsError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik nie zawiera żadnych rozdań.
        /// </summary>
        internal static string Form1_analyzeNoDealsError {
            get {
                return ResourceManager.GetString("Form1_analyzeNoDealsError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Otwieram plik.
        /// </summary>
        internal static string Form1_analyzeOpenFile {
            get {
                return ResourceManager.GetString("Form1_analyzeOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd.
        /// </summary>
        internal static string Form1_error {
            get {
                return ResourceManager.GetString("Form1_error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd wczytywania pliku.
        /// </summary>
        internal static string Form1_fileOpenError {
            get {
                return ResourceManager.GetString("Form1_fileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można utworzyć pliku. Sprawdź, czy w katalogu programu istnieje katalog &apos;files&apos;.
        /// </summary>
        internal static string Form1_generateFileNotFoundError {
            get {
                return ResourceManager.GetString("Form1_generateFileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisano do pliku.
        /// </summary>
        internal static string Form1_generateFileSaved {
            get {
                return ResourceManager.GetString("Form1_generateFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd generatora.
        /// </summary>
        internal static string Form1_generateGeneratorError {
            get {
                return ResourceManager.GetString("Form1_generateGeneratorError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd wprowadzania danych.
        /// </summary>
        internal static string Form1_generateInputError {
            get {
                return ResourceManager.GetString("Form1_generateInputError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu IMP.
        /// </summary>
        internal static string ScoreAccumulator_IMP {
            get {
                return ResourceManager.GetString("ScoreAccumulator_IMP", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu max.
        /// </summary>
        internal static string ScoreAccumulator_MP {
            get {
                return ResourceManager.GetString("ScoreAccumulator_MP", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu  KONTRAKT      LEWY    ZAPIS   WYGRA?  MAX    IMP.
        /// </summary>
        internal static string ScoreAccumulator_txtHeader {
            get {
                return ResourceManager.GetString("ScoreAccumulator_txtHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu obie po.
        /// </summary>
        internal static string ScoreAccumulator_vulBoth {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulBoth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu EW po.
        /// </summary>
        internal static string ScoreAccumulator_vulEW {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulEW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Założenia.
        /// </summary>
        internal static string ScoreAccumulator_vulnerability {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu obie przed.
        /// </summary>
        internal static string ScoreAccumulator_vulNone {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulNone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NS po.
        /// </summary>
        internal static string ScoreAccumulator_vulNS {
            get {
                return ResourceManager.GetString("ScoreAccumulator_vulNS", resourceCulture);
            }
        }
    }
}
